name: Rust Test

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Testing Algorithms
      working-directory: Rust/algo
      run: cargo test --verbose
    - name: Testing Data Structures
      working-directory: Rust/ds
      run: cargo test --verbose
    - name: Testing Math code
      working-directory: Rust/maths
      run: cargo test --verbose
